openapi: 3.0.1

paths:

  #####################################################
  # Payment Confirmation Service
  #####################################################

  /v1/payment-confirmation-service:

    post:
      summary: Payment confirmation request
      description:
      operationId: initiatePayment
      tags:
        - Payment Confirmation Service (PIS)

      security:
      #####################################################
      # REMARKS ON SECURITY IN THIS OPENAPI FILE
      #In this file only the basic security element to transport
      # the bearer token of an an OAuth2 process, which has to
      # be included inthe HTTP header ist described.
      #
      # WARNING:
      # If you want to use this file for a productive implementation,
      # it is recommandes to adjust the security schemes according to
      # your system enviroments and security policies.
      #####################################################
        - {}
        - BearerAuthOAuth: []

      parameters:
      #path
        - $ref: "#/components/parameters/paymentService"
        - $ref: "#/components/parameters/paymentProduct"
      #query # NO QUERY PARAMETER
      #header
          #common header parameter
        - $ref: "#/components/parameters/X-Request-ID"
          #header to support the signature function
        - $ref: "#/components/parameters/Digest"
        - $ref: "#/components/parameters/Signature"
        - $ref: "#/components/parameters/TPP-Signature-Certificate"
          #method specific header elements
        - $ref: "#/components/parameters/PSU-ID"
        - $ref: "#/components/parameters/PSU-ID-Type"
        - $ref: "#/components/parameters/PSU-Corporate-ID"
        - $ref: "#/components/parameters/PSU-Corporate-ID-Type"
        - $ref: "#/components/parameters/consentId_HEADER_optional"
        - $ref: "#/components/parameters/PSU-IP-Address_mandatory"
        - $ref: "#/components/parameters/TPP-Redirect-Preferred"
        - $ref: "#/components/parameters/TPP-Redirect-URI"
        - $ref: "#/components/parameters/TPP-Nok-Redirect-URI"
        - $ref: "#/components/parameters/TPP-Explicit-Authorisation-Preferred"
        - $ref: "#/components/parameters/TPP-Rejection-NoFunds-Preferred"
          #conditional for extended service lean Push
        - $ref: "#/components/parameters/TPP-Notification-URI"
        - $ref: "#/components/parameters/TPP-Notification-Content-Preferred"
          #optional additional PSU Information in header
        - $ref: "#/components/parameters/PSU-IP-Port"
        - $ref: "#/components/parameters/PSU-Accept"
        - $ref: "#/components/parameters/PSU-Accept-Charset"
        - $ref: "#/components/parameters/PSU-Accept-Encoding"
        - $ref: "#/components/parameters/PSU-Accept-Language"
        - $ref: "#/components/parameters/PSU-User-Agent"
        - $ref: "#/components/parameters/PSU-Http-Method"
        - $ref: "#/components/parameters/PSU-Device-ID"
        - $ref: "#/components/parameters/PSU-Geo-Location"

      requestBody:
        $ref: "#/components/requestBodies/paymentInitiation"

      responses:
        '201':
          $ref: "#/components/responses/CREATED_201_PaymentInitiation"

        '400':
          $ref: "#/components/responses/BAD_REQUEST_400_PIS"
        '401':
          $ref: "#/components/responses/UNAUTHORIZED_401_PIS"
        '403':
          $ref: "#/components/responses/FORBIDDEN_403_PIS"
        '404':
          $ref: "#/components/responses/NOT_FOUND_404_PIS"
        '405':
          $ref: "#/components/responses/METHOD_NOT_ALLOWED_405_PIS"
        '406':
          $ref: "#/components/responses/NOT_ACCEPTABLE_406_PIS"
        '408':
          $ref: "#/components/responses/REQUEST_TIMEOUT_408_PIS"
        '409':
          $ref: "#/components/responses/CONFLICT_409_PIS"
        '415':
          $ref: "#/components/responses/UNSUPPORTED_MEDIA_TYPE_415_PIS"
        '429':
          $ref: "#/components/responses/TOO_MANY_REQUESTS_429_PIS"
        '500':
          $ref: "#/components/responses/INTERNAL_SERVER_ERROR_500_PIS"
        '503':
          $ref: "#/components/responses/SERVICE_UNAVAILABLE_503_PIS"



  /v1/payment-confirmation-service/{paymentId}:

    get:
      summary: Get Payment Information
      description: Returns the content of a payment object
      operationId: getPaymentInformation
      tags:
        - Payment Initiation Service (PIS)
      security:
      #####################################################
      # REMARKS ON SECURITY IN THIS OPENAPI FILE
      #In this file only the basic security element to transport
      # the bearer token of an an OAuth2 process, which has to
      # be included inthe HTTP header ist described.
      #
      # WARNING:
      # If you want to use this file for a productive implementation,
      # it is recommandes to adjust the security schemes according to
      # your system enviroments and security policies.
      #####################################################
        - {}
        - BearerAuthOAuth: []
      parameters:
      #path
        - $ref: "#/components/parameters/paymentService"
        - $ref: "#/components/parameters/paymentProduct"
        - $ref: "#/components/parameters/paymentId"
      #query # NO QUERY PARAMETER
      #header
          #common header parameter
        - $ref: "#/components/parameters/X-Request-ID"
          #header to support the signature function
        - $ref: "#/components/parameters/Digest"
        - $ref: "#/components/parameters/Signature"
        - $ref: "#/components/parameters/TPP-Signature-Certificate"
          #optional additional PSU Information in header
        - $ref: "#/components/parameters/PSU-IP-Address_optional"
        - $ref: "#/components/parameters/PSU-IP-Port"
        - $ref: "#/components/parameters/PSU-Accept"
        - $ref: "#/components/parameters/PSU-Accept-Charset"
        - $ref: "#/components/parameters/PSU-Accept-Encoding"
        - $ref: "#/components/parameters/PSU-Accept-Language"
        - $ref: "#/components/parameters/PSU-User-Agent"
        - $ref: "#/components/parameters/PSU-Http-Method"
        - $ref: "#/components/parameters/PSU-Device-ID"
        - $ref: "#/components/parameters/PSU-Geo-Location"
      #NO REQUEST BODY

      responses:
        '200':
          $ref: "#/components/responses/OK_200_PaymentInitiationInformation"

        '400':
          $ref: "#/components/responses/BAD_REQUEST_400_PIS"
        '401':
          $ref: "#/components/responses/UNAUTHORIZED_401_PIS"
        '403':
          $ref: "#/components/responses/FORBIDDEN_403_PIS"
        '404':
          $ref: "#/components/responses/NOT_FOUND_404_PIS"
        '405':
          $ref: "#/components/responses/METHOD_NOT_ALLOWED_405_PIS"
        '406':
          $ref: "#/components/responses/NOT_ACCEPTABLE_406_PIS"
        '408':
          $ref: "#/components/responses/REQUEST_TIMEOUT_408_PIS"
        '409':
          $ref: "#/components/responses/CONFLICT_409_PIS"
        '415':
          $ref: "#/components/responses/UNSUPPORTED_MEDIA_TYPE_415_PIS"
        '429':
          $ref: "#/components/responses/TOO_MANY_REQUESTS_429_PIS"
        '500':
          $ref: "#/components/responses/INTERNAL_SERVER_ERROR_500_PIS"
        '503':
          $ref: "#/components/responses/SERVICE_UNAVAILABLE_503_PIS"

    delete:
      summary: Payment Cancellation Request
      description: |
        This method initiates the cancellation of a payment.
        Depending on the payment-service, the payment-product and the ASPSP's implementation,
        this TPP call might be sufficient to cancel a payment.
        If an authorisation of the payment cancellation is mandated by the ASPSP,
        a corresponding hyperlink will be contained in the response message.

        Cancels the addressed payment with resource identification paymentId if applicable to the payment-service, payment-product and received in product related timelines (e.g. before end of business day for scheduled payments of the last business day before the scheduled execution day).

        The response to this DELETE command will tell the TPP whether the
          * access method was rejected
          * access method was successful, or
          * access method is generally applicable, but further authorisation processes are needed.
      operationId: cancelPayment
      tags:
        - Payment Confirmation Service (PIS)

      security:
      #####################################################
      # REMARKS ON SECURITY IN THIS OPENAPI FILE
      #In this file only the basic security element to transport
      # the bearer token of an an OAuth2 process, which has to
      # be included inthe HTTP header ist described.
      #
      # WARNING:
      # If you want to use this file for a productive implementation,
      # it is recommandes to adjust the security schemes according to
      # your system enviroments and security policies.
      #####################################################
        - {}
        - BearerAuthOAuth: []

      parameters:
      #path
        - $ref: "#/components/parameters/paymentService"
        - $ref: "#/components/parameters/paymentProduct"
        - $ref: "#/components/parameters/paymentId"
      #query # NO QUERY PARAMETER
      #header
          #common header parameter
        - $ref: "#/components/parameters/X-Request-ID"
          #header to support the signature function
        - $ref: "#/components/parameters/Digest"
        - $ref: "#/components/parameters/Signature"
        - $ref: "#/components/parameters/TPP-Signature-Certificate"
        - $ref: "#/components/parameters/TPP-Redirect-Preferred"
        - $ref: "#/components/parameters/TPP-Nok-Redirect-URI"
        - $ref: "#/components/parameters/TPP-Redirect-URI"
        - $ref: "#/components/parameters/TPP-Explicit-Authorisation-Preferred"
          #optional additional PSU Information in header
        - $ref: "#/components/parameters/PSU-IP-Address_optional"
        - $ref: "#/components/parameters/PSU-IP-Port"
        - $ref: "#/components/parameters/PSU-Accept"
        - $ref: "#/components/parameters/PSU-Accept-Charset"
        - $ref: "#/components/parameters/PSU-Accept-Encoding"
        - $ref: "#/components/parameters/PSU-Accept-Language"
        - $ref: "#/components/parameters/PSU-User-Agent"
        - $ref: "#/components/parameters/PSU-Http-Method"
        - $ref: "#/components/parameters/PSU-Device-ID"
        - $ref: "#/components/parameters/PSU-Geo-Location"
      #NO REQUEST BODY

      responses:
        '204':
          $ref: "#/components/responses/NO_CONTENT_204_PaymentInitiationCancel"
          #If the DELETE is sufficient for cancelling the payment
        '202':
          $ref: "#/components/responses/RECEIVED_202_PaymentInitiationCancel"
          #If the DELETE is not sufficient for cancelling the payment since an authorisation of the cancellation by the PSU is needed.

        '400':
          $ref: "#/components/responses/BAD_REQUEST_400_PIS"
        '401':
          $ref: "#/components/responses/UNAUTHORIZED_401_PIS"
        '403':
          $ref: "#/components/responses/FORBIDDEN_403_PIS"
        '404':
          $ref: "#/components/responses/NOT_FOUND_404_PIS"
        '405':
          $ref: "#/components/responses/METHOD_NOT_ALLOWED_405_PIS_CANC"
        '406':
          $ref: "#/components/responses/NOT_ACCEPTABLE_406_PIS"
        '408':
          $ref: "#/components/responses/REQUEST_TIMEOUT_408_PIS"
        '409':
          $ref: "#/components/responses/CONFLICT_409_PIS"
        '415':
          $ref: "#/components/responses/UNSUPPORTED_MEDIA_TYPE_415_PIS"
        '429':
          $ref: "#/components/responses/TOO_MANY_REQUESTS_429_PIS"
        '500':
          $ref: "#/components/responses/INTERNAL_SERVER_ERROR_500_PIS"
        '503':
          $ref: "#/components/responses/SERVICE_UNAVAILABLE_503_PIS"